      SUBROUTINE PRJECT(M,I,MTO,NBAS,NCOL,CONST,CLEAR,DSRY,DPL,DMN
     1                 ,COSN,SINN,COEF
     2                 ,MT,MALPH,MBETA,MGAM,MTAU,KTAU,L,LP1,INVER)
C-----------------------------------------------------------------------
C SUBROUTINE APPLIES THE PROJECTION OPERATOR TO REAL SPHERICAL HARMONICS
C-----------------------------------------------------------------------
      IMPLICIT REAL*8 (A-H,O-Z)
      PARAMETER (LMAX=48)
      PARAMETER (N48=48)
      PARAMETER (NBASMX=100)
      PARAMETER (LMAXP1=LMAX+1)
      DIMENSION COEF(N48,LMAXP1,2,NBASMX,3)
      DIMENSION DPL(LMAXP1,LMAXP1,8),DMN(LMAXP1,LMAXP1,8),DSRY(N48,3)
      DIMENSION COSN(LMAXP1,12),SINN(LMAXP1,12)
      DIMENSION MT(N48,N48),MALPH(N48),MBETA(N48),MGAM(N48)
      LOGICAL CLEAR
      IF(NBAS.GT.NBASMX) GO TO 100
      IF(NCOL.GT.3) GO TO 100
      IF(.NOT.CLEAR) GO TO 1
      DO 15 M1=1,LP1
      DO 15 MT1=1,MTAU
      DO 15 I1=1,2
      COEF(MT1,M1,I1,NBAS,NCOL)=0.D0
   15 CONTINUE
C     PROJECTION OF YL(L,M,I)
    1 IPMAX=1
      MP=0
30    CONTINUE
      DO 51 IP=1,IPMAX
      DO 6 KT=1,KTAU
      IMALPH=MALPH(KT)
      IMGAM=MGAM(KT)
      IMBETA=MBETA(KT)
      IF(I.EQ.2) GO TO 7
      IF(IP.EQ.2) GO TO 10
      D= COSN(MP+1,IMALPH)*COSN(M+1,IMGAM)*DPL(MP+1,M+1,IMBETA)
     1  -SINN(MP+1,IMALPH)*SINN(M+1,IMGAM)*DMN(MP+1,M+1,IMBETA)
      GO TO 9
    7 IF(IP.EQ.2) GO TO 8
      D=-COSN(MP+1,IMALPH)*SINN(M+1,IMGAM)*DPL(MP+1,M+1,IMBETA)
     1  -SINN(MP+1,IMALPH)*COSN(M+1,IMGAM)*DMN(MP+1,M+1,IMBETA)
      GO TO 9
    8 D=-SINN(MP+1,IMALPH)*SINN(M+1,IMGAM)*DPL(MP+1,M+1,IMBETA)
     1  +COSN(MP+1,IMALPH)*COSN(M+1,IMGAM)*DMN(MP+1,M+1,IMBETA)
      GO TO 9
   10 D= SINN(MP+1,IMALPH)*COSN(M+1,IMGAM)*DPL(MP+1,M+1,IMBETA)
     1  +COSN(MP+1,IMALPH)*SINN(M+1,IMGAM)*DMN(MP+1,M+1,IMBETA)
    9 IF(KT.GT.INVER.AND.MOD(L,2).NE.0) D=-D
      INNN=MT(KT,MTO)
    6 COEF(INNN,MP+1,IP,NBAS,NCOL)
     1   =COEF(INNN,MP+1,IP,NBAS,NCOL)+DSRY(KT,NCOL)*D*CONST
   51 CONTINUE
      IPMAX=2
      MP=MP+1
      IF(MP.LE.L) GO TO 30
      RETURN
 100  WRITE(14,110) KT,MTO,MT(KT,MTO),MP,IP,NBAS,NCOL,M,I
      STOP
 110  FORMAT(' KT=',I5,' MTO=',I5,' MT=',I5,' MP=',I5,' IP=',I5,' NBAS='
     S,I5,' NCOL=',I5,' M=',I5,' I=',I5,/,40X,'STOP IN PRJECT')
      END
